
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head/>
      <body style={{fontFamily: 'ui-sans-serif'}}>
        {children}
      </body>
    </html>
  );
}
